[tool.poetry]
name = "python-template"
version = "0.0.1"
description = ""
authors = ["mozkzki"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.7"

[tool.poetry.dev-dependencies]
flake8 = "3.9.2"
mypy = "0.910"
pytest = "6.2.5"
black = "21.9b0"
pytest-cov = "2.12.1"
coverage = "5.5"
isort = "5.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
